// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3C3zUSe52UcoQHEf-hfs4HB155GlZ-k',
    appId: '1:785869779309:web:0396379a1a0a128a41aa64',
    messagingSenderId: '785869779309',
    projectId: 'blood-donation-app-60518',
    authDomain: 'blood-donation-app-60518.firebaseapp.com',
    storageBucket: 'blood-donation-app-60518.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp3HQZBjiu5sQBVIlL4JI-Pejhi9CXtRQ',
    appId: '1:785869779309:android:44d47b70b8d9b0fb41aa64',
    messagingSenderId: '785869779309',
    projectId: 'blood-donation-app-60518',
    storageBucket: 'blood-donation-app-60518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkXyMtunNH-rL3iu7WexjcbV3XkPm6zx8',
    appId: '1:785869779309:ios:21d5aeac9b01b94441aa64',
    messagingSenderId: '785869779309',
    projectId: 'blood-donation-app-60518',
    storageBucket: 'blood-donation-app-60518.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkXyMtunNH-rL3iu7WexjcbV3XkPm6zx8',
    appId: '1:785869779309:ios:21d5aeac9b01b94441aa64',
    messagingSenderId: '785869779309',
    projectId: 'blood-donation-app-60518',
    storageBucket: 'blood-donation-app-60518.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3C3zUSe52UcoQHEf-hfs4HB155GlZ-k',
    appId: '1:785869779309:web:65d990a7ef884f3841aa64',
    messagingSenderId: '785869779309',
    projectId: 'blood-donation-app-60518',
    authDomain: 'blood-donation-app-60518.firebaseapp.com',
    storageBucket: 'blood-donation-app-60518.firebasestorage.app',
  );
}
